firstjoin_message: '&a<player> &7is about to witness the horrors of this server for the first time'
join_message: '&e<player> &7has returned to this abomination of a server'
leave_message: '&e<player> &7has left this war crime of a server'